version: "3.9"

services:

  graycat-gpu:
    build: .
    container_name: graycat-gpu
    ports: 
      - "1337:1337"
    environment:

      # Configuration Variables
      - GPU_LAYERS=${GPU_LAYERS}
      - REMOTE=${REMOTE}
      # Remote Variables
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASS=${REDIS_PASS}
      - MODEL_URL=${MODEL_URL}
      - LLAMA_SERVER_URL=${LLAMA_SERVER_URL}
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
